### ISSUE TITLE
Feature request: focus VM window when user input is required

### ISSUE THREAD

**Issue by daviunic** [laciba96/WinBox-for-86Box#11]
**Describe the feature you want to request**
When performing actions on a VM that require user input (e.g. requesting a shutdown, which triggers a confirmation dialog in 86Box), the VM window should be focused by Winbox so it's brought to the front.

**Give some reasons why it would be good for anyone else**
If you have multiple windows open, several minimized VMs, etc., it's faster to confirm the shutdown/something else if the window is automatically focused and brought to the front, so you don't have to look through all the windows to find it.

**Describe the solution you'd like**
Can be done with the Win32 API SetForegroundWindow, which takes a window handle parameter.

**Describe alternatives you've considered**
None

**Additional context**
A small usability enhancement.

**Comment by laciba96** [comment]
The new [release](https://github.com/laciba96/WinBox-for-86Box/releases/tag/v1.0.0.627) contains the feature.
