### ISSUE TITLE
Feature request: double-clicking a VM in the list starts/stops it

### ISSUE THREAD

**Issue by daviunic** [laciba96/WinBox-for-86Box#12]
**Describe the feature you want to request**
When you double-click on a VM in the list, it should be started if it's not running, or stopped if it is (this part is optional, starting is more important to me personally).

**Give some reasons why it would be good for anyone else**
It's a small usability improvement, some people are more used to double-clicking on list items rather than looking for a button or pressing keys.

**Describe the solution you'd like**
Should probably be a fairly easy implementation.

**Describe alternatives you've considered**
None.

**Comment by laciba96** [comment]
The new [release](https://github.com/laciba96/WinBox-for-86Box/releases/tag/v1.0.0.627) contains the feature.
For running VMs, instead of stopping it brings the VM to the front, starting VMs now works as you described.
