### ISSUE TITLE
Bug: WinBox hangs when a VM is waiting for user input

### ISSUE THREAD

**Issue by daviunic** [laciba96/WinBox-for-86Box#13]
**Describe the bug**
When an action that requires user input is performed through WinBox (e.g. stopping a VM, hard reset, etc.), WinBox will hang until the user responds. This prevents you from managing other VMs when one is left waiting for the user.

I'm not entirely sure if this is a bug or intended behaviour, as I don't know your implementation of these features. However, personally I think it's bad design if it's on purpose - not just because it reduces usability (can't do anything until that one VM is resumed), but also because it's just not a friendly thing to see a program hang for no apparent reason. The user may think WinBox has crashed for some other reason - an asynchronous design would make more sense here in my opinion.

**To Reproduce**
1. Start a VM.
2. In WinBox, click on e.g. "H/W reset" button.
3. Leave the VM waiting and observe that WinBox is now hanged until the dialog box in 86Box is closed.

**Technical informations (please complete the following information):**
- OS: Windows 10 Pro 21H1 x64
- WinBox for 86Box Version: v1.0.0.624
- 86Box Version: any recent build

**Comment by laciba96** [comment]
The new [release](https://github.com/laciba96/WinBox-for-86Box/releases/tag/v1.0.0.627) contains the fix. 
In theory it's fixed, but if the problem came up again feel free to create another issue.
