### ISSUE TITLE
Program updater is broken, even on regular installations

### ISSUE THREAD

**Issue by maxdlpee** [laciba96/WinBox-for-86Box#21]
**Describe the bug**
When trying to search for program updates (Tools-Search for Program Updates...) the error message shown on the screenshot is displayed. As you might be able to guess, this is not intentional.

1. Go to 'Tools'
2. Click on 'Search for Program Updates...'
3. See error

[**Screenshots**]

![pic1](https://user-images.githubusercontent.com/77379259/134173495-174d2610-553e-429d-8e5f-c3a1347e061f.png)

**Technical information:**
- OS: Windows 10 21H1 [Spanish language and ES-ES locale]
- WinBox for 86Box Version: 1.0.0.723 (I recall it happening on the previous Winbox version though)
- WinBox Installation Folder: C:\Users\(username)\AppData\Local\Programs\Laci bá'\WinBox for 86Box

**Log file about the error**

[Error log.log](https://github.com/laciba96/WinBox-for-86Box/files/7203187/Error.log.log)

**Additional context**
My Internet connection was functioning properly at the time the error message was displayed.
Update management on Program Settings was set to "Installer download, automatic installation" at the time the log was generated, but I've tried all four settings with the same results.

**Comment by laciba96** [comment]
Currently I can't reproduce your error, so I have to ask some questions to be able to do it.

1, Does the emulator update working, or also produces the same error?
2, How fast you get this dialog? I meaning, for example almost instant when clicking to the Program Update menu item, or you have to wait a little bit.

**Comment by maxdlpee** [comment]
1: Yes, that works properly.
2: If I had to guess, around 1 or 2 seconds after clicking.

**Comment by laciba96** [comment]
Thank you for the answers, but I have to say currently I still have no idea, how can I reproduce this error. (The first answer was suprising for me.)

In order to find the cause of the problem, I created a special debug version of the program, which will dump a lot of stuff to the console. You can simply extract it and start from anywhere, all your settings will be loaded from the registry.

[winbox-dbg-pupd.723.zip](https://github.com/laciba96/WinBox-for-86Box/files/7203927/winbox-dbg-pupd.723.zip)

Can you repeat the steps you described above and send me the whole contents of the console?

**Comment by maxdlpee** [comment]
Here it is:
[Console.txt](https://github.com/laciba96/WinBox-for-86Box/files/7203975/Console.txt)

**Comment by laciba96** [comment]
Okay we are getting closer to the causes. 
It seems the code for pinging the remote server fails somewhy at your side. 

[winbox-dbg-ping.723.zip](https://github.com/laciba96/WinBox-for-86Box/files/7204071/winbox-dbg-ping.723.zip)
.
Can you repeat the steps with this version?
I've extended it with additional debug console texts near at the pinging code.

**Comment by maxdlpee** [comment]
Here:
[Console2.txt](https://github.com/laciba96/WinBox-for-86Box/files/7204093/Console2.txt)

**Comment by laciba96** [comment]
Okay, it can't ping `api.github.com` somewhy, but can ping `ci.86box.net`. 
For a quick test I remove the pinging code, to check if that was the only problem.

[winbox-test-pupd.723.zip](https://github.com/laciba96/WinBox-for-86Box/files/7204121/winbox-test-pupd.723.zip)

If only this was the problem, hopefully this is the last debug build I ask you to repeat the steps.

**Comment by maxdlpee** [comment]
Ok, now this dialog shows up, which I think is what it is supposed to do:
![pic2](https://user-images.githubusercontent.com/77379259/134194671-475663e4-0527-44d6-a1bf-3678457e8b5c.png)

**Comment by laciba96** [comment]
Yes it should open that, so the version checking is done.
And I also found a translation typo in the dialog you sent. xD

Okay, I work out a fix soon, and release a new version. 
Thank you for the debugging, and the kind assistance.
