### ISSUE TITLE
Flickering problem

### ISSUE THREAD

**Issue by DimMan88** [laciba96/WinBox-for-86Box#39]
Flickering inside 86Box Window (VM) is happening when I have the Notification area option to "Minimize to the system tray icon" . This also happening at the HW settings of each VM without booting them. 
![unknown](https://user-images.githubusercontent.com/71668463/144721612-b36d70c1-46ca-436e-bf1a-c6d03d109b2f.png)

Here are the videos:
https://cdn.discordapp.com/attachments/266245173036449794/914201824884576256/2021-11-27_19-09-11.mkv

https://cdn.discordapp.com/attachments/266245173036449794/916778037176057967/2021-12-04_21-41-33-1.mp4

Host Specs:
Intel i5-3330
12GB DDR3 RAM
AMD R7 360 2GB
Windows 10 Pro 64bit 21H2

**Comment by laciba96** [comment]
Thank you for the detailed report, and the videos. I'll surely check what can I do about this case.

**Comment by laciba96** [comment]
I could reproduce your bug, added a fix, and my internal test were also successful. 
The fix is available with v1.0.0.976.

**Comment by DimMan88** [comment]
THANK YOU
