### ISSUE TITLE
Sorting by certain fields results in an error in the Hard Disk Database dialog

### ISSUE THREAD

**Issue by johnnovak** [laciba96/WinBox-for-86Box#53]
**Before you start please read [this guide about reporting bugs.](https://github.com/laciba96/WinBox-for-86Box/wiki/Contribution-Guide#accepted-form-of-issues)**

**Describe the bug**

Sorting by certain fields results in an error in the Hard Disk Database dialog:

![bug](https://user-images.githubusercontent.com/698770/147892183-98c2ce55-3365-46ea-9415-858957558d5b.png)

**To Reproduce**

1. Press New Disk button
2. Select Virtual Hard DIsk
3. Select "Selection from Hard Disk Database"
4. Try to sort by these fields: **Manufacturer**, **Size**, **Model**, **Connector**. All these will throw an exception, the rest works as expected.

**Technical informations (please complete the following information):**
- OS: WIndows 10
- WinBox v1.1.0.356

**Log file about the error**

[WinBox.exe-exception-2022-01-03_09-25-51.log](https://github.com/laciba96/WinBox-for-86Box/files/7799932/WinBox.exe-exception-2022-01-03_09-25-51.log)

**Comment by laciba96** [comment]
I've could reliably reproduce this error based on your instructions, and found the cause. The database engine, and the translation system was stuck together, that raised the problem. Commited a fix, it will comes with the next release.
